services:
  development-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"

volumes:
  postgres_volume:
